---
title: "Apply it to your Data 1"
author: "Dean Stone"
date: "2023-02-16"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE)

library(tidyverse)
library(tidymodels)
library(usemodels)
library(textrecipes)
library(vip)
library(ggplot2)
```

## Import Data

```{r}
transit_cost <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-01-05/transit_cost.csv')
```

## Explore Data
```{r}
transit_cost %>%
    select(e, cost, length, tunnel, stations) %>%
    pivot_longer(length:stations, names_to = "specs") %>%
    ggplot(aes(value, cost, color = specs)) +
    geom_point(alpha = 0.4, show.legend = FALSE) +
    scale_y_log10() + 
    scale_x_log10() +
    facet_wrap(~specs, scales = "free_x") +
    labs(x = NULL)
```

```{r}
transit_cost_df <- transit_cost %>%
    select(cost, city, country, length, tunnel, stations) %>%
    mutate(cost = log10(cost))%>%
    mutate_if(is.character, factor) %>%
    
    # Remove -Inf in cost
    filter(cost != -Inf)
```

## Build a Model

```{r}
set.seed(123)
transit_split <- initial_split(transit_cost_df, strata = cost)
transit_train <- training(transit_split)
transit_test <- testing(transit_split)

set.seed(234)
transit_folds <- bootstraps(transit_train, strata = cost)
transit_folds
```

```{r}
use_ranger(cost ~ ., data = transit_train)
```

```{r}
ranger_recipe <- 
  recipe(formula = cost ~ ., data = transit_train) %>%
    step_impute_knn(city, country, length, tunnel, stations)

ranger_spec <- 
  rand_forest(mtry = tune(), min_n = tune(), trees = 1000) %>% 
  set_mode("regression") %>% 
  set_engine("ranger") 

ranger_workflow <- 
  workflow() %>% 
  add_recipe(ranger_recipe) %>% 
  add_model(ranger_spec) 

ranger_fit <- fit(ranger_workflow, transit_train)

set.seed(99799)
doParallel::registerDoParallel()
ranger_tune <-
  tune_grid(ranger_workflow, 
            resamples = transit_folds, 
            grid = 11)
```

## Explore Results

```{r}
show_best(ranger_tune, metric = "rmse")

# How did all the possible parameter combinations do?
autoplot(ranger_tune)
```


We can finalize our random forest workflow with the best performing parameters.
```{r}
final_rf <- ranger_workflow %>% 
    finalize_workflow(select_best(ranger_tune, "rmse"))
```

The function last_fit() fits this finalized random forest one last time to the training data and evaluates one last time on the testing data.
```{r}
transit_fit <- last_fit(final_rf, transit_split)
transit_fit
```

## Evaluate model

```{r}
collect_metrics(transit_fit)
collect_predictions(transit_fit)
```

```{r}
collect_predictions(transit_fit) %>%
    ggplot(aes(cost, .pred)) +
    geom_point(alpha = 0.5, fill = "midnightblue") +
    geom_abline(lty = 2, color = "gray50") +
    coord_fixed()
```

